### ISSUE TITLE
AMP - Cartoons do not render in recommended content

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#11971] opened 2016-02-15 11:55 UTC
In the recommended content containers at the bottom of the amp pages, cartoon pages do not render.
example:

bottom container of recommendations on page: https://amp.theguardian.com/politics/2016/feb/15/lords-overruled-recording-laws-vellum-goat-calf-skin

![image](https://cloud.githubusercontent.com/assets/7239344/13048043/117b731e-d3db-11e5-8192-7c276cca7a5f.png)

**Comment by NataliaLKB** [comment] 2016-02-16 18:57
This will be fixed with @TBonnin 's change. Related to #11972.

Mind you, we should add a fix to say if each content object is empty, don't show. this will mean a blank space will show instead. What do you think Thomas?

**Comment by TBonnin** [comment] 2016-02-17 14:27
The problem seems to be the container endpoint returning empty items. We should probably fix this

**Comment by TBonnin** [comment] 2016-02-18 16:15
This can't be reproduced at the moment and unless Cartoons become the first container of a Section front or one of the first 4 containers of a network front it won't be visible on an amp page.
(See https://github.com/guardian/frontend/pull/12000 to see the containers we show on amp pages)
Closing for now.

**Closed by TBonnin** 2016-02-18 16:15 UTC
Labels: Amp
