### ISSUE TITLE
Sticky nav - back button - lag in processing selection and page jump on navigating back to a front from an article

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#10245] opened 2015-08-24 10:29 UTC
If you press back on an android device to get from a content page back to a front, there is a lag between the page being drawn and the sticky nav jumping in and pushing content down. this lag is long enough to see and select a story.
What makes it really bad is - if you happen to select a story before sticky nav is drawn and content jumps, the position of your selection on the screen is only processed after the sticky nav comes in and content jumps.
This means that you end up selecting a different story to the one you clicked on!

To reproduce:
On an android device, scroll down to a story on the 2nd or 3rd container
Open the story
Press the back button to go back to the homepage (this takes you back to the front you were on with the same scroll position you had when you selected the content

Result:
Page loads ok, with no sticky nav present.
After a few seconds delay, the sticky nav pops in at the top and the content of the page is pushed downwards.
If you select a story before the sticky nav jumps in, the position you tapped on your screen is only read  after the nav is drawn and the resulting jump happens. Consequently you are taken to a completely different story.

**Comment by OliverJAsh** [comment] 2015-08-25 12:56
This is related to (maybe even a duplicate of) https://github.com/guardian/frontend/issues/10147

**Comment by ScottPainterGNM** [comment] 2015-10-02 08:26
Having discussed with @stephanfowler - as we will reimplement mobile before it coming back on, this bug is closed for now but needs to be considered for when we revisit this.

**Closed by ScottPainterGNM** 2015-10-02 08:26 UTC
Labels: a11y, bug, sticky-nav
