### ISSUE TITLE
Firefox - Key events on liveblog overlap sharing button if you open then close full size image lightbox

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9614] opened 2015-06-26 10:38 UTC
In a liveblog, select the "maximise" option to see main image full size, then close the lightbox containing the full size image.
Result:
The liveblog page redisplays, but key events list overlaps the sharing buttons.
Scrolling down the page resolves the issue.

![image](https://cloud.githubusercontent.com/assets/7239344/8375722/d29a6664-1bf7-11e5-8762-99393af1bfb7.png)

**Comment by paperboyo** [comment] 2015-06-26 10:50
Reproduced on FF 38.0.5, Chrome 43, Safari 7.0.6 on 10.9.5. Possibly related to https://github.com/guardian/frontend/issues/8121.

**Comment by JonNorman** [comment] 2016-04-01 15:42
Just tried reproducing this, but with no success; shall we close it?

I tried the following links:
- http://www.theguardian.com/politics/blog/live/2016/mar/24/osborne-budget-treasury-committee-trump-vote-to-leave-eu-because-of-immigration-craziness-politics-live
- http://www.theguardian.com/business/live/2016/mar/29/european-stocks-rally-oil-bank-of-england-port-talbot-live

**Comment by paperboyo** [comment] 2016-04-01 15:47
^ what @JonNorman said, fine here too.

**Closed** 2016-04-01 16:12 UTC
Labels: bug, sustain
