### ISSUE TITLE
Expand/collapse arrows using text instead of icon on fronts

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#10497] opened 2015-09-14 09:52 UTC
![image](https://cloud.githubusercontent.com/assets/36964/9847100/984faff8-5ace-11e5-9ad1-58e203a43fb5.png)

Possibly on purpose? But the icon is still there in the DOM, just `display: none`'d, so could be a bug?

**Comment by gtrufitt** [comment] 2015-09-22 13:07
This looks like it's expected behaviour, the styles haven't been touched in months and the icon is shown on narrow but not desktop - @crifmulholland @Pearson82 can you confirm this is what we want (and do you want to make any updates?)

![image](https://cloud.githubusercontent.com/assets/638051/10019090/36414fcc-6133-11e5-9b2c-3c703f74d7a7.png)

![image](https://cloud.githubusercontent.com/assets/638051/10019100/4394f52a-6133-11e5-9ff7-124b834828a9.png)

**Comment by Pearson82** [comment] 2015-09-22 13:13
Yeah thats correct that the icon should be there for mobile but not at wider breakpoints. @theefer @gtrufitt Not sure about the display: none though

**Comment by gtrufitt** [comment] 2015-09-22 13:14
Ok cool, thanks, will close this off. The display: none is in a wide breakpoint (icon is hidden above tablet mq).

**Closed by gtrufitt** 2015-09-22 13:14 UTC
Labels: sustain
