### ISSUE TITLE
Liveblogs - Guardian witness images not rendering on android devices

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7701] opened 2015-01-08 17:02 UTC
Guardian Witness images embedded in liveblogs are not rendering on android devices.
I have tried a Moto G running A4.4.4 and Samsung GS2 running A4.1. iPhones seem to render ok.

**Comment by ScottPainterGNM** [comment] 2015-05-11 11:13
Finer on newer Samsung phone but reproduced on GS2, first couple of images load but following that just an image placeholder.

**Comment by tonytw1** [comment] 2015-05-11 11:19
I look after Witness. The images are served from S3.
If this turns out to be an issue on the Witness side, let me the details and I'll try to follow it up.

**Comment by johnduffell** [comment] 2015-07-08 13:44
closing this as it hasn't been fixed so far and probably won't be fixed in the near future

**Closed by johnduffell** 2015-07-08 13:44 UTC
Labels: bug, content, Reproduced
