### ISSUE TITLE
Memory leak on article page leads to 3GB tab

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#17820] opened 2017-09-19 11:38 UTC
I had a tab on my machine get to about 3 GB this morning. 
My edition cookie is set to "AU"
The url was https://www.theguardian.com/commentisfree/2017/sep/19/wheres-the-biff-free-speech-has-won-every-round-in-the-marriage-equality-debate#comment-105435099
As you can see the page jumped straight to a comment - might be relevant.
In the network tab I could see a lot of errors to do with VPAID (the video injection ads)

**Comment by michaelwmcnamara** [comment] 2017-09-19 11:40
Another user based in Australia has seen this issue several times.
Usually when he has opened an article in a new tab with the intention of reading it later.
He also saw vpaid.js making a large number of requests when he opened the chrome debugger on the offending tab.

**Comment by SiAdcock** [comment] 2018-05-21 21:26
I find this issue interesting and surprising, because from what I can tell, vpaid tech was removed a year and a half earlier in #12052.

Have you seen this problem occur more recently @michaelwmcnamara? Can you remember what browser you were using?

**Comment by SiAdcock** [comment] 2018-10-26 15:03
I have failed to recreate this issue. I guess vpaid is a thing of the past and perhaps Chrome is a bit better at memory management too. I’ll close this for now, feel free to reopen if you see a regression

**Closed by SiAdcock** 2018-10-26 15:03 UTC
Labels: bug, commercial, confirmed
