### ISSUE TITLE
firefox - link to comment does not take you to the comment

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#10471] opened 2015-09-10 15:44 UTC
links to comment are not working for any page type.
eg: http://www.theguardian.com/crosswords/quick/14146#comment-59152565

The page loads but scroll does not jump to the linked comment
![image](https://cloud.githubusercontent.com/assets/7239344/9792991/16142640-57db-11e5-9fe7-d0994171bbc2.png)

Severity of this issue is increased as it also applies to the "view discussion" link in commnets and replies on your profile page.
eg a user who wants to view the discussion around the comment he made would click on this link to go straight there, however because this is broken he has to search through the  hundreds of comments that have since been added in order to deliver his brilliant riposte.

**Comment by crifmulholland** [comment] 2015-09-10 15:48
Which browser did you manage to recreate this on?

**Comment by ScottPainterGNM** [comment] 2015-09-10 15:52
I tried on firefox and if you click the direct link like the one linked above it didn't scroll down but if I click on a time to create a comment permalink then the scroll worked?

![permalink firefox](https://cloud.githubusercontent.com/assets/11922253/9793235/51e77c3e-57dc-11e5-90f6-94065650cf5a.gif)

**Comment by ScottPainterGNM** [comment] 2015-09-10 16:10
I'm having issues with the permalink not jumping to pages on non crosswords with Firefox as well, going to flag up for sustain rather than loyalty.

**Comment by michaelwmcnamara** [comment] 2015-09-11 10:21
Issue found on firefox 40.0.3 running on OSX Yosimite

**Comment by paperboyo** [comment] 2015-09-11 11:34
Reproduced now on 40.0.3 on 10.9.5, but observed for long time on different OSes/FF versions. It couldn't possibly be related to https://github.com/guardian/frontend/issues/10331 (and, then, to https://github.com/guardian/frontend/issues/9927 & https://github.com/guardian/frontend/issues/8338), could it? :laughing:

**Comment by paperboyo** [comment] 2015-10-10 18:56
Can’t reproduce any more. Possibly fixed by https://github.com/guardian/frontend/pull/10829? Safe to close?

**Comment by paperboyo** [comment] 2015-10-11 09:28
Doesn’t work on IE11 & Edge on Windows 10 either. Sometimes just clicking reload helps, sometimes it doesn’t. Chrome & Opera unaffected.

**Comment by gidsg** [comment] 2016-05-17 10:06
Closing as duplicate of #12678

**Closed by gidsg** 2016-05-17 10:06 UTC
Labels: bug, sustain
