### ISSUE TITLE
Football - Match Stats don't display at Mobile Breakpoint

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9979] opened 2015-07-30 11:43 UTC
The match stats on match reports and live blogs showing key data disappear at the mobile breakpoint but should appear at the bottom of the report (according to the football team).

![screen shot 2015-07-30 at 12 42 53](https://cloud.githubusercontent.com/assets/11922253/8982373/87cba81a-36b8-11e5-9ca1-dfcc39dd3064.png)

**Comment by jennysivapalan** [comment] 2015-07-31 15:55
Related this to #9974

I tested this locally by pushing the date we fetch date from PA back by 90 days. The stats came through and displayed at the bottom for mobile and on the side for desktop.

**Comment by jennysivapalan** [comment] 2015-08-03 09:45
@ScottPainterGNM I've checked this against the game over the weekend and it seems to be working fine for the mobile breakpoint. 
http://www.theguardian.com/football/2015/aug/02/community-shield-arsenal-chelsea-oxlade-chamberlain

![screen shot 2015-08-03 at 10 29 17](https://cloud.githubusercontent.com/assets/944375/9034836/b2e7c050-39ca-11e5-9663-79f091511a84.png)

The text for Today's matches is now incorrect and doesn't show on desktop (as it's a drop down). Not sure what would be best to substitute this with,  maybe Match details?

**Comment by jennysivapalan** [comment] 2015-08-04 12:18
Closing as confirmed with football editorial team that data is showing up fine.

**Closed by jennysivapalan** 2015-08-04 12:18 UTC
Labels: bug, football, priority: high
