### ISSUE TITLE
unfilled ad slot causes page indent in text

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8079] opened 2015-01-29 14:05 UTC
An unfilled ad slot causes page indent in text.
This is visible in preview on page: http://preview.gutools.co.uk/books/2015/jan/31/terrorism-spectacle-how-states-respond-yuval-noah-harari-sapiens

screenshot:
bug:
![image](https://cloud.githubusercontent.com/assets/7239344/5958756/08417b1a-a7c0-11e4-919b-a41ce5c76f3e.png)

with debugger open:
![image](https://cloud.githubusercontent.com/assets/7239344/5958737/d04ec0fa-a7bf-11e4-806c-d428980d0774.png)

**Comment by ScottPainterGNM** [comment] 2015-04-29 08:46
This seems to be fine now, cannot reproduce the issue and text appears to be aligned correctly now so closing issue off unless it reappears.

**Closed by ScottPainterGNM** 2015-04-29 08:46 UTC
Labels: bug, content
