### ISSUE TITLE
Resizing window after page load causes live blog scrolling to jump (Chrome / OSX)

### ISSUE THREAD

**Issue by LorneStenhauer** [guardian/frontend#10049] opened 2015-08-06 11:27 UTC
To reproduce:
1) Load live article (ie Ashes coverage) in a maximised window
2) Resize window horizontally (ie to one half of the screen)
3) scrolling up or down now seems to skip a large chunk of space, usually around the events summary

**Comment by heralder99** [comment] 2015-08-06 11:28
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <[frontend] Resizing window after page load causes live blog scrolling to jump (Chrome / OSX) (#10049)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by rich-nguyen** [comment] 2015-08-11 10:24
Hi @LorneStenhauer thanks for the bug report. Can you tell us which browser and machine you were using? I've tried to reproduce the issue but the scrolling was ok.

Depending on the severity of the issue, we may flag resize window issues as won't fix, because they are typically uncommon and highly variable in behaviour, and often hard to repro and fix.

**Comment by rich-nguyen** [comment] 2015-08-17 08:17
Closing, as mentioned above, can't reproduce, and it doesn't seem widespread. Do let us know if you have any more details.

**Closed by rich-nguyen** 2015-08-17 08:17 UTC
Labels: sustain
