### ISSUE TITLE
Timestamp and permalink wrong on newly posted comment

### ISSUE THREAD

**Issue by Smylers** [guardian/frontend#6864] opened 2014-10-30 12:39 UTC
I posted a comment, and, without refreshing the page, the timestamp for it displayed as ‘4h ago’. Also its permalink was to the non-existent: http://discussion.theguardian.com/comment-permalink/0

Loading the same page in another tab, the timestamp changed to the correct ‘2m ago’, and the permalink had the correct comment ID in it. So the bug was only present while still on the page that posted the comment.

After posting a second comment (while still on the first tab), both of them had this problem.

All other timestamps seemed to be correct; that is, they were the same across both of my tabs, with only my comments differing by 4 hours.

**Comment by ScottPainterGNM** [comment] 2015-04-24 13:20
@gidsg I am working through the old issues list and wondered whether you are happy for me to post in that comments thread to see if I can reproduce this again?

**Comment by gidsg** [comment] 2015-04-24 13:22
@ScottPainterGNM sure, go ahead.

**Comment by ScottPainterGNM** [comment] 2015-04-28 08:50
Having tested this I cannot reproduce the issue with the wildly incorrect time stamp but it does default to show 2m ago when I post a comment even when checking straight away.

**Comment by Smylers** [comment] 2015-04-28 10:30
> it does default to show 2m ago when I post a comment even when checking straight away.

Was it also still missing the link to your username and the arrow and username indicating who it was in reply to?

**Comment by johnduffell** [comment] 2015-07-08 12:56
closing this as it hasn't been fixed so far and probably won't be fixed in the near future

**Closed by johnduffell** 2015-07-08 12:56 UTC
Labels: bug, Reproduced
