### ISSUE TITLE
Sorting buttons inactive

### ISSUE THREAD

**Issue by zenonp** [guardian/frontend#9359] opened 2015-06-03 11:02 UTC
As of yesterday afternoon, the "Order by", "Show" and "Threads" buttons no longer work. They do appear as links to the browser (pointer turns to hand), but they do not react to clicking. As a result, it is impossible to use any other settings than the default sort by newest, show 25 and threads collapsed. The latter is particularly annoying, as it also blocks Ctrl-F searches in the browser. 

Seen yesterday and today on every random article where tried, with Firefox 38.0 ESR ("Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0") running on SL7.1 (RHEL 7.1) with javascript enabled, irrespective of whether loggged in or not.

**Comment by zenonp** [comment] 2015-06-03 12:33
Same problem with a fresh installation of Opera ("Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16").

**Comment by rich-nguyen** [comment] 2015-06-03 12:52
Thanks, @zenonp. This is a duplicate of #9343, and will be fixed soon in #9354

**Closed by rich-nguyen** 2015-06-03 12:52 UTC
