### ISSUE TITLE
Liveblog key events scroll user too far

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/frontend#10242] opened 2015-08-24 10:13 UTC
Looks like the scroll to anchor feature on the liveblogs isn't compensating for the sticky navigation. Which means when I click on a key event I can't read the title, like this...

![screen shot 2015-08-24 at 11 09 22](https://cloud.githubusercontent.com/assets/1607666/9437799/edea1a36-4a50-11e5-84bc-efb2a8916521.png)

When I should get...

![screen shot 2015-08-24 at 11 09 17](https://cloud.githubusercontent.com/assets/1607666/9437805/f47f0bae-4a50-11e5-90e2-c39bc05c6774.png)

It also looks like the 'key events' title gets get off too, while it doesn't look broken I'm not sure that's the intended design.

**Comment by OliverJAsh** [comment] 2015-08-25 12:58
Duplicate of https://github.com/guardian/frontend/issues/9963 and https://github.com/guardian/frontend/issues/9917

The sticky nav has broken all "jump to anchor" things, some of which we've fixed with hacks. :cry:

**Closed** 2015-09-03 09:14 UTC
