### ISSUE TITLE
Empty CTAs in Soulmates component

### ISSUE THREAD

**Issue by zeftilldeath** [guardian/frontend#11386] opened 2015-12-17 11:00 UTC
Empty CTAs. Been on the site like this for at least a month now. 

![screen shot 2015-12-17 at 10 57 51](https://cloud.githubusercontent.com/assets/14570016/11868061/211b8794-a4ad-11e5-9415-446485053096.png)

**Comment by ScottPainterGNM** [comment] 2016-04-04 09:01
@uplne Did we change to new Soulmates components now or are these still live?

**Comment by uplne** [comment] 2016-04-04 09:13
@ScottPainterGNM It was a request from commercial components team to allow buttons without text. I think they are testing it so it is not a bug.

However the buttons looks like they have an empty space instead of text so they appear to be broken. So we should possibly look at making it look nicer.

**Comment by ScottPainterGNM** [comment] 2016-04-04 09:15
Fair enough, will ask Shraddah to add to health backlog.

**Comment by kelvin-chappell** [comment] 2016-04-06 14:09
Is there a URL where we can see this happening?

**Comment by ScottPainterGNM** [comment] 2016-04-07 11:02
Closing off as this component is no longer in use

**Closed by ScottPainterGNM** 2016-04-07 11:02 UTC
Labels: commercial
