### ISSUE TITLE
Multiple IPad User Issues

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9082] opened 2015-05-01 09:27 UTC
User help have sent a number of issues through reported by IPad users where the site continually crashes and reloads, they are using Safari across multiple different IPad types (2,3,4) but all using IOS 8.3.

**Comment by ScottPainterGNM** [comment] 2015-06-01 14:30
Just to add to this issue, we have had people feeding back that they are moving from the site to the app due to the site crashing. Having discussed with users some of them have the iPad4 running latest iOS and this is crashing. We have replicated on Safari and Chrome.

**Comment by ScottPainterGNM** [comment] 2015-06-01 14:34
@stephanfowler this is the one I just mentioned!

**Comment by foiseworth** [comment] 2015-06-05 12:34
I am happy to test any fix for this. Currently guardian is the only website I have issues with - it crashes my ipad browser and somteimes os on 2 out of 3 visits to the homepage. Both Chrome and Safari suffer from the same issue which I presume is because they uiwebview.

**Comment by johnduffell** [comment] 2015-07-08 15:59
we know all about the perf issues and are focussing on them so we don't need to track it here.

**Closed by johnduffell** 2015-07-08 15:59 UTC
Labels: bug, Prio 1, Reproduced

**Comment by foiseworth** [comment] 2015-07-08 19:38
@johnduffell the site crashing the web browser isn't a performance issue. I've stopped using the guardian on my ipad it so reliably crashes it.

Do you test the site on an iPad internally? I'm surprised you aren't experiencing the same issues.

**Comment by johnduffell** [comment] 2015-07-09 10:13
Yes sorry I mistyped there.  But we are really acutely aware of the issues with iOS, the issues are basically that safari increases in memory so much that ios kills it off in an abrupt manner.  We know that the problem is that the site is too heavy for safari in terms of DOM size, CSS, and to a small degree Javascript.  However it turns out that removing code/features, especially when people rely on them is at least as difficult as adding them.  For example, we flipped a switch last month to move iPad 2 to a lower functionality level and we got a lot of user feedback about that, so we know we need to keep features working!  Rest assured that iPad/iPhone crashes are something our small team is discussing nearly every day, and over the next quarter we hope to improve this as much as possible.
