### ISSUE TITLE
Safari - Market indicators - Display broken by resizing window

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#7841] opened 2015-01-16 17:35 UTC
Load economy or business page with window at full size.
Resize to 1059' width 
economy widgets jump to top of page, however they are displayed across rows rather than all showing in 1 row.

![screen shot 2015-01-16 at 17 14 07](https://cloud.githubusercontent.com/assets/7239344/5780898/111ba02c-9da6-11e4-8569-03cce31ca8d0.png)

**Comment by ScottPainterGNM** [comment] 2015-04-29 09:01
Cannot reproduce this issue so closing off, when changing between breakpoints the market indicators jump to the top of the page into a tidy row now.

**Closed by ScottPainterGNM** 2015-04-29 09:01 UTC
Labels: bug, fronts
