### ISSUE TITLE
Video player UX and UI small bugs

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10898] opened 2015-10-19 12:28 UTC
Hello,

After a recent update to videojs:

- [x] a fullscreen button is misplaced to the left of volume slider (it should be on the far right) [EDIT: fixed by amazing and selfless @jamesgorrie in https://github.com/guardian/frontend/pull/13062]

- [x] double-clicking to enter/exit fullscreen no longer works [EDIT: fixed by https://github.com/guardian/frontend/pull/11846. Thanks!]

- [ ] moving mouse off the video should hide controls much faster

Regards
Mateusz

**Comment by rich-nguyen** [comment] 2015-10-19 12:43
For the first issue, that's a change in the DOM provided by videojs. I didn't think we should fight against it, we are already arbitrarily floating some of the buttons right, and i couldn't think of a reason why we should go against videojs's standard ordering.

For the second issue, that's a plugin of ours that I didn't get round to updating, will do so.

thanks @paperboyo

**Comment by paperboyo** [comment] 2015-10-19 12:56
> couldn't think of a reason why we should go against videojs's standard ordering

Because it’s absurd? I haven’t seen _a single_ video player in my life that would be using this ordering. Also, we owe it to our users not to change things randomly. Also, default v. 5 skin seems to have a button on the far right: http://codepen.io/heff/pen/EarCt.  Also, check this out: https://github.com/guardian/frontend/pull/5860#issuecomment-54692339.

I can’t stress how strongly I feel about this, I even think they will just change this back if indeed that’s what they did. Obviously, decision’s not mine.

> For the second issue

Thanks a lot, @rich-nguyen!

**Comment by paperboyo** [comment] 2015-10-19 13:01
https://github.com/videojs/video.js/issues/2688

**Comment by rich-nguyen** [comment] 2015-10-19 13:03
I'm happy to go with videojs ordering. I believe that full screen button should be Bottom Right, however, the cause of the inconsistency isn't due to placing the fullscreen, it's to do with randomly choosing to float other things to the right (I mean the volume bar, which ought to stay left), which forces the fullscreen to lose it's far-right position. If we can get some agreement to move those controls, then the full screen button will naturally find it's way back to it's correct position. As I said, let's not fight the standard ordering implied by the videojs DOM.

**Comment by paperboyo** [comment] 2015-10-19 13:08
Sorry, I misunderstood. You seem to be talking about not messing around with videojs’s code. Which, from what you’re saying, we already do and if we stop doing it, the button will be back to where it should be. I’m all for it! You see, I do not care - I just want the button to be on the far right. If the code will be clearer - that’s superb.

**Comment by paperboyo** [comment] 2015-10-19 13:09
> If we can get some agreement to move those controls

How would we do it? Is there anything I can do to help (like pestering someone)?

**Comment by rich-nguyen** [comment] 2015-10-19 13:10
yes, i will show you how to pester the right person. pop over.

**Comment by paperboyo** [comment] 2015-10-19 13:12
Cool! I just need to know the victim, the rest is in my blood. Tomorrow, though, when I’m back at work :palm_tree: :laughing:

**Comment by paperboyo** [comment] 2015-11-19 10:10
Just to add that the lack of doubleclick-to-fullscreen makes small videos on fronts almost unusable - since they do not have enough space for the (tragically displaced) fullscreen button...

**Comment by paperboyo** [comment] 2015-12-21 12:22
Hello,

Both issues are still present. Deputy Head of Video (who still can't get used to the awkward placement of fs button, nor should he) just noted that there is one more possible victim of the update:

Apparently, we had fixed the duration of the control bar showing over video to be much shorter. I should disappear as soon as the user moves the mouse off video*. This is now back to how it should not be (i.e. to how it was before we fixed it).

If you think that opening two separate issues will help to track these bugs, let me know.

* the other popular video service works exactly like that. But if the mouse is touched when on-the-video, the control bar stays a bit longer (~3s).

Regards
Mateusz

**Comment by rich-nguyen** [comment] 2015-12-21 13:59
Thanks @paperboyo, we can track them both here. Will try to pick this up if I get time

**Comment by paperboyo** [comment] 2015-12-21 14:05
No, thank you, @rich-nguyen. And sorry to be a pain before Xmas. :christmas_tree:

**Comment by jamesgorrie** [comment] 2016-02-04 12:25
Fullscreen button should be fixed here #11846 
FS button - should that be on the left of the volume control? i.e.

All left to right
```
Left: Play || Time
Right: Embed || Volume || Fullscreen
```

Interaction with controls:
```
Mouse over: show controls
No movement: Wait a bit -> hide
Mouseout: Hide controls
```

Is this what you're thinking?

**Comment by paperboyo** [comment] 2016-02-04 12:46
> `Right: Embed || Volume || Fullscreen`

Yes!

> `Mouse over: show controls; No movement: Wait a bit -> hide; Mouseout: Hide controls`
 
Yes. Moving mouse off the video should hide controls much faster (as it was adjusted by us before it broke). Stalling the mouse over the video should hide controls a bit slower (maybe current ~2s is fine?).

**Comment by paperboyo** [comment] 2016-04-21 10:05
Misplaced fullscreen button plays havoc with the new Video container (https://github.com/guardian/frontend/pull/12584) on mobile. Because player is small there and because the button is still misplaced, there is a (redundant on mobile) volume rocker showing but fullscreen button is **not showing** which makes it near impossible to go fullscreen (unless double-tap). I know that there are grand plans for video player, but I still strongly believe we should fix the fullscreen button misplacement immediately. Immediately half a year ago that is :stuck_out_tongue_winking_eye:

@sammorrisdesign @jamesgorrie @akash1810 @mymomandherdog

![screenshot_2016-04-21-11-03-30](https://cloud.githubusercontent.com/assets/6032869/14705330/db6c5d60-07b0-11e6-89b8-cef81e78dbeb.png)

**Comment by paperboyo** [comment] 2016-04-21 10:07
Of course this affect all small-card videos on mobile fronts! Video container just provided a convenient excuse for me to bump this issue...

**Comment by jamesgorrie** [comment] 2016-04-21 10:42
We're working on the series page first and then will be looking at working through the bits and bobs of the video container.

**Comment by jamesgorrie** [comment] 2016-05-26 11:22
> much faster

**Closed by jamesgorrie** 2016-05-26 11:22 UTC
Labels: video
