### ISSUE TITLE
Crosswords front redesign

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25314] opened 2022-08-01 09:53 UTC
wide
![image](https://user-images.githubusercontent.com/19683595/182124884-c48c768b-85f5-4930-ba64-94344bdf8cfa.png)

leftCol
![image](https://user-images.githubusercontent.com/19683595/182124823-ccce5a21-3a86-431c-a403-4451805f5013.png)

**Comment by jlieb10** [comment] 2022-08-01 10:59
To-do: Ioanna to try CSS-only solution, if that doesn't work we should backlog and ask the Crosswords team to look into whether or not this space is being used effectively and for its intended purpose, as there does seem to be a lot more content here than in other containers. There may be a better place for it on the site, so we could pass to UX or Editorial to think about that.

**Comment by ioannakok** [comment] 2022-08-02 09:17
Renamed this issue and will leave it open for the reasons @jlieb10 says above

**Comment by AshCorr** [comment] 2023-04-25 15:25
@ioannakok we're not quite sure what the issue is! Do we still need to work on this?

**Comment by rhiannareechaye** [comment] 2023-04-27 13:31
Closing this as we're not sure what the issue is and we have over 130 health tickets!

**Closed by rhiannareechaye** 2023-04-27 13:31 UTC
