### ISSUE TITLE
Opt-in message is broken in IE9

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#7103] opened 2014-11-13 14:47 UTC
Looks like this for me (on [this](http://www.theguardian.com/uk?view=mobile#opt-in-message) URL):

![screen shot 2014-11-13 at 14 47 35](https://cloud.githubusercontent.com/assets/394376/5029996/06ee7c62-6b44-11e4-9d78-1c7c8f9f8f05.png)

**Comment by paperboyo** [comment] 2015-01-31 17:12
Non-applicable any more? Safe to close?

**Comment by davidrapson** [comment] 2015-02-02 09:53
@paperboyo Still applicable I think. `ie9.global.css` is still over the selector limit so some styles will be ignored. Currently this is largely the new-site banner, but I think it's worth looking at getting [grunt-bless](https://github.com/Ponginae/grunt-bless) in place for the IE9 stylesheet.

![screen shot 2015-02-02 at 09 50 13](https://cloud.githubusercontent.com/assets/123386/5998612/379baa30-aac1-11e4-83ac-f3882b6e810e.png)

**Comment by paperboyo** [comment] 2015-02-02 09:58
Ah! You're right. My bad, sorry, I - wrongly - presumed the message is gone for good. Forgot the site is new; it's an old hat to me ;-)

Regards
Mateusz

**Comment by phamann** [comment] 2015-02-02 10:01
We had this same issue last year and was the selector limit. We will be deleting a very large amount of CSS over the next two days as part of our performance workshop, which should solve the problem. 

/cc @austinh7

**Comment by davidrapson** [comment] 2015-02-02 10:06
@phamann Sounds good, I guess the ideal way is to keep below the selector limit completely if possible. Any plans to add a `ie9.global.css` to the dashboard, maybe with an alert on no. of selectors to catch this in future?

**Comment by ScottPainterGNM** [comment] 2015-04-29 08:24
Although now the message surrounding the international edition beta the message still has display issue, screenshot below (Reproduced in IE9): 

![screen shot 2015-04-29 at 09 25 18](https://cloud.githubusercontent.com/assets/11922253/7387014/7f010e14-ee51-11e4-84bd-84497e990705.png)

**Comment by davidrapson** [comment] 2015-05-05 09:41
@ScottPainterGNM Hey Scott, glad this has been reproduced.

FWIW the banner display is the symptom not the cause. There are missing styles in IE9 because the stylesheet is over the [selector limit](http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx), so the banner happens to be missing styles because the associated CSS is past that limit; this will affect any styles that are over that limit.

**Comment by johnduffell** [comment] 2015-07-08 13:08
closing this as it hasn't been fixed so far and probably won't be fixed in the near future

**Closed by johnduffell** 2015-07-08 13:08 UTC
Labels: bug, design input required, Reproduced
