### ISSUE TITLE
Cannot sign into account using Google Auth 

### ISSUE THREAD

**Issue by turkeyphant** [guardian/frontend#19252] opened 2018-03-01 12:01 UTC
# ISSUE
Cannot sign into accounts through Google account. 

## Steps to Reproduce
Visit theguardian.com, tap menu and sign in or visit https://profile.theguardian.com/signin?INTCMP=DOTCOM_NEWHEADER_SIGNIN

Tap sign in via Google which redirects to app where you must press the sign in button again. 

## Actual Results (include screenshots)
![screenshot_2018-02-28-12-52-35](https://user-images.githubusercontent.com/8129583/36843836-1aa83810-1d48-11e8-9ffa-06207e9ef8be.png)

## Expected Results (include screenshots)
User is signed into account. 

## OS and Browser details

- Device: LG G5 (H850) 
- Browser (inc version): Chrome 64.0.3282.137 
- OS: Android 7.0

*Please add relevant labels*

**Comment by jfsoul** [comment] 2018-03-01 14:15
Thanks for reporting this @turkeyphant - we believe the issue is now fixed.

**Closed by jfsoul** 2018-03-01 14:15 UTC

**Comment by turkeyphant** [comment] 2018-09-17 09:59
STILL NOT FIXED!
