### ISSUE TITLE
No print link (or print CSS)

### ISSUE THREAD

**Issue by mattandrews** [guardian/frontend#7107] opened 2014-11-13 16:46 UTC
A user mentioned this on a comment thread – NGW has no "print" link for an article (or print CSS). Is this planned...?

**Comment by paperboyo** [comment] 2015-01-31 17:24
Duplicate of https://github.com/guardian/frontend/issues/5971, https://github.com/guardian/frontend/issues/1277.

The existing print style, still lacking though (FF - left, Chrome - right, IE11* - bottom):

![print](https://cloud.githubusercontent.com/assets/6032869/5988944/b826b2da-a96d-11e4-9f93-a238dc77f9ee.PNG)

*the lack of webfonts on IE11 is caused by inability of IE11 on Win 10 TP to deal with data URI-embedded fonts (IE11 on Win 8.1 is fine): http://answers.microsoft.com/en-us/insider/forum/insider_ie-insider_browse/fonts-embedded-as-data-uri-do-not-display-in-ie11/a6fa26a8-2e83-4347-a192-94c80973d63d

**Comment by ScottPainterGNM** [comment] 2015-05-11 09:22
@mattandrews @paperboyo Looking at Chrome and FF it appears that the print preview is considerably better then it was previously, are you happy to close this issue off?

**Comment by mattandrews** [comment] 2015-05-11 09:24
Sounds good to me, well done all :)

**Closed** 2015-05-11 09:33 UTC
