### ISSUE TITLE
Add reading time markers to article pages?

### ISSUE THREAD

**Issue by StephenAbbott** [guardian/frontend#6099] opened 2014-09-24 09:53 UTC
Building on the 'time trilogy' apps that @rrees made using the (slightly hacky) word count queries in the content API, would there be any interest from the Guardian team in introducing an estimated reading time marker/field on Guardian beta article pages? Has this already been tested internally?

http://gu-tickticktick.appspot.com/
http://gu-word-count.appspot.com/

![tumblr_mo0xlfu2ku1qbaxlqo1_400](https://cloud.githubusercontent.com/assets/1506468/4386436/8044c6ca-43d0-11e4-93f6-80e2fb69d526.gif)
Keep up the good work!

**Comment by ScottPainterGNM** [comment] 2015-04-23 14:20
As we are clearing the issues list down I will close this off as not a bug, if this is still desired then please re-open.

**Closed by ScottPainterGNM** 2015-04-23 14:20 UTC
