### ISSUE TITLE
Byline and co. invisible under showcased embed

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9089] opened 2015-05-02 17:11 UTC
Hello,

I thought it was fixed long ago, but apparently not. All browsers on Win 8.1. On two widest breakpoints article meta furniture (including sharing buttons!) is covered by the embedded main media if it’s set to showcase.

URL e.g.: http://www.theguardian.com/lifeandstyle/2015/may/01/last-bites-david-everitt-mathias-final-meal

Hard to do a screenshot of something not being there, but can do if needed ;-)

Regards
Mateusz

**Comment by ScottPainterGNM** [comment] 2015-05-05 09:03
Also reproduced in Chrome

**Comment by johnduffell** [comment] 2015-07-08 16:02
since no-one has looked at this yet, it probably won't be looked at soon

**Comment by paperboyo** [comment] 2015-07-08 16:05
Oh, no-no-no! This one is serious! E.g. makes it impossible to showcase (or brakes showcased regardless) anything in this series http://www.theguardian.com/lifeandstyle/2015/jul/03/josceline-dimbleby-final-meal-last-bites.

Please reopen, as I don't have privileges...

**Comment by paperboyo** [comment] 2015-07-08 16:05
Alternatively, keep https://github.com/guardian/frontend/issues/9171 open (it's a duplicate).

**Comment by johnduffell** [comment] 2015-07-08 16:31
reopening as this is causing problems for users

**Comment by paperboyo** [comment] 2015-07-08 16:31
Thanks, @johnduffell!

**Comment by rich-nguyen** [comment] 2015-08-13 13:20
Neither of these articles have main media elements. The first showcased element is in the body. Closing, as the fix for this is to add the element as main media in composer.

**Closed by rich-nguyen** 2015-08-13 13:20 UTC
Labels: sustain

**Comment by gtrufitt** [comment] 2019-01-29 14:24
Discussing with @zeftilldeath to make a call and / or design decision on this.

**Comment by philmcmahon** [comment] 2019-04-17 16:56
@gtrufitt this is also an issue when an interactive is used as the main media and set to showcase https://composer.code.dev-gutools.co.uk/content/5cb758388f0843eff6921eb4

**Comment by paperboyo** [comment] 2019-05-13 10:52
> kinda odd as it doesn't do it when an image is used as showcase

It doeas: https://github.com/guardian/frontend/issues/21399
