### ISSUE TITLE
AMP - captions on images have extra top padding

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#11966] opened 2016-02-12 18:59 UTC
<img width="559" alt="screen shot 2016-02-12 at 18 58 29" src="https://cloud.githubusercontent.com/assets/2236852/13017132/a9adfd1e-d1ba-11e5-9add-d51802b133cc.png">

https://amp.theguardian.com/music/2015/nov/12/prince-interview-paisley-park-studios-minneapolis

@NataliaLKB @zeftilldeath

**Comment by NataliaLKB** [comment] 2016-02-16 19:14
@Jholder112233 Thanks for catching this!

The problem is we have a block share element there between the picture and the caption. The svgs are being loaded, but just don't have any styling. @stephanfowler @zeftilldeath do we want to show more share buttons (style these), or should I remove them?

**Comment by Jholder112233** [comment] 2016-02-17 13:13
Hey @NataliaLKB, looks like the .rounded-icon class has display: inline-block on it, so the height of the "inline-expand-image" span is still there. Going to be one for an !important sadly!

**Comment by NataliaLKB** [comment] 2016-02-17 13:25
Yes, you are right! I will try to think of a way to not use `!important`

**Comment by Jholder112233** [comment] 2016-02-17 13:27
Maybe the cleanest solution is to clean them out of the dom in the first place?

I wouldn't be worried about putting an !important in for AMP though, feels like a valid use. (I've put plenty of them in the codebase when necessary for overrides)

**Comment by NataliaLKB** [comment] 2016-02-17 13:29
Yes I think cleaning them out in the first place is the answer - as we don't show them at all on mobile anyway.

**Comment by NataliaLKB** [comment] 2016-02-17 15:49
Closing! Works on code now: http://amp.code.dev-theguardian.com/music/2015/nov/12/prince-interview-paisley-park-studios-minneapolis

Thanks @Jholder112233  :smile:

**Closed by NataliaLKB** 2016-02-17 15:49 UTC
Labels: Amp
