### ISSUE TITLE
IE9 - Comment horizontal takeover "Joker" in "New voices and opinions" Does not scale

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#6944] opened 2014-11-04 14:36 UTC
Navigate to US front.
Scroll down to "New voices and opinions" container where the new comment banner exhibiting new commenter is displayed.
The banner displays far too large for the window and does not scale:

![screen shot 2014-11-04 at 14 34 10](https://cloud.githubusercontent.com/assets/7239344/4901265/00242e1a-6430-11e4-9947-e2cb60def585.png)

**Comment by ScottPainterGNM** [comment] 2015-04-24 09:06
Related issue seems to have been resolved and cannot reproduce the original issue so closing off issue unless it reappears.

**Closed by ScottPainterGNM** 2015-04-24 09:06 UTC
Labels: bug, fronts
