### ISSUE TITLE
Images on eyewitness pages are requested at the wrong resolution

### ISSUE THREAD

**Issue by gtrufitt** [guardian/frontend#10666] opened 2015-09-28 14:10 UTC
The images on [eyewitness showcase](http://www.theguardian.com/world/picture/2015/sep/28/eyewitness-france) are being requested at the wrong at the wrong resolution for different breakpoints.

At greater than 990px widths the image is being rendered at 940px wide, when natural width is 700px.

Related to #10467, #9482, #10493

**Comment by paperboyo** [comment] 2015-09-28 14:35
Eyewitness is a part of Cartoon/Picture type, so a duplicate of https://github.com/guardian/frontend/issues/10467, I think? But thanks a lot, because nobody reads my issues :wink:

**Comment by gtrufitt** [comment] 2015-09-28 14:36
@paperboyo Ah, you could be right. Will leave this open until I've confirmed that 😀

**Comment by paperboyo** [comment] 2016-01-23 17:32
This has been fixed by https://github.com/guardian/frontend/pull/10852. Safe to close, I believe.

**Comment by ScottPainterGNM** [comment] 2016-04-04 12:41
Sweet!

**Closed by ScottPainterGNM** 2016-04-04 12:41 UTC
Labels: sustain
