### ISSUE TITLE
Old article in the most viewed in Film front

### ISSUE THREAD

**Issue by ioannakok** [guardian/frontend#25320] opened 2022-08-01 14:44 UTC
![Image](https://user-images.githubusercontent.com/19683595/182175576-1517bd14-194f-46be-a0a3-aaa2248111f9.png)

From Ophan it seems there is a spike in the traffic of this article:
https://www.theguardian.com/film/video/2013/oct/18/the-broken-circle-breakdown-video
https://dashboard.ophan.co.uk/info?capi-id=film/video/2013/oct/18/the-broken-circle-breakdown-video

Kibana: https://logs.gutools.co.uk/s/dotcom/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(columns:!(),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'50201630-bd0f-11e9-92b3-f10623802d36',key:req.header.X-GU-GeoCountry,negate:!f,params:(query:%22IR%22),type:phrase),query:(match_phrase:(req.header.X-GU-GeoCountry:%22IR%22)))),index:'50201630-bd0f-11e9-92b3-f10623802d36',interval:auto,query:(language:lucene,query:%22film%2Fvideo%2F2013%2Foct%2F18%2Fthe-broken-circle-breakdown-video%22),sort:!(!('@timestamp',desc)))

**Comment by jlieb10** [comment] 2022-08-02 10:25
Copied from chat:
thanks @Ioanna Kokkini - yes, i think this issue is not caused by anything technical so isn't for us to "fix" - the most viewed algorithm is rightly identifying this article as the most viewed in this section, but it's because of bot-generated/inorganic traffic (from diffuse IP addresses, so can't be blocked on that basis). 

It is for editorial to decide on what we do for cases like this (if anything). While it is true that the article is receiving the most traffic, it is also the case that the traffic (as far as I understand) is inorganic or generated by inorganic leads. I was thinking @Victoria Duczek-Woodward would be a good person to ask about who we should speak to and enable that meeting.

One of the ideas that came out of the retro on the very old poorly-written self-harm article that made it into the most popular section - attended by @James Gorrie, not sure who else - was the idea to scrap section-specific Most Viewed containers in favour of a global one. This might be even easier to do once we are developing Deeply Read - we could in theory enable Deeply Read on a section-specific basis without running the same risk of promoting bot traffic.

**Comment by jlieb10** [comment] 2022-08-02 10:26
We should leave this in play, but we do not have any action to take on it at this stage. One for discussion.

**Comment by jlieb10** [comment] 2022-08-03 09:43
Closing this as Editorial are fine with this as is - will put back into play if they want to pursue the conversation

**Closed by jlieb10** 2022-08-03 09:43 UTC
